### ISSUE TITLE
Backlog for 1.2a

### ISSUE THREAD

**Issue by tanweijie123** [AY2021S1-CS2103T-T13-3/tp#76]
- [ ] Create Test cases for Session & Schedule. 

- [x] Refactor UniqueTList<T> to UniqueList<T>

- [x] Refactor isExisting() to isUnique() 
   - isUnique checks for unique identifer. (weak equality)

**Comment by benclmnt** [comment]
Closing to wrap up 1.2.. Will create issues for point 1 (#115 , #90 )
